<?php

namespace Database\Seeders;

use App\Models\Datel;
use App\Models\Lokasi;
use App\Models\Token;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LokasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $lokasis = [
            [
                "_id" => "601c3fb236a7bb18138e0aaf",
                "witel" => "KALBAR",
                "datel" => "PONTIANAK",
                "lokasi" => "WITEL/STO PTK",
                "timezone" => "WIB",
                "listrik" => [
                    [
                        "nomor_pln" => "211000397237",
                        "ukuran" => "32423432",
                        "daya" => "555",
                    ],
                    [
                        "nomor_pln" => "211001847907",
                        "ukuran" => "4324435534",
                        "daya" => "240",
                    ],
                    ["nomor_pln" => "211000396106", "daya" => "147"],
                ],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ab0",
                "witel" => "KALBAR",
                "datel" => "PONTIANAK",
                "lokasi" => "SAIGON",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211011105348", "daya" => "13.2"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ab1",
                "witel" => "KALBAR",
                "datel" => "PONTIANAK",
                "lokasi" => "MSC TA",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211000397142", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ab2",
                "witel" => "KALBAR",
                "datel" => "PONTIANAK",
                "lokasi" => "SUNGAI RAYA",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211000588041", "daya" => "23"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ab3",
                "witel" => "KALBAR",
                "datel" => "PONTIANAK",
                "lokasi" => "PIL",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211000890200", "daya" => "41.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ab4",
                "witel" => "KALBAR",
                "datel" => "PONTIANAK",
                "lokasi" => "JAWI",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211001152348", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ab5",
                "witel" => "KALBAR",
                "datel" => "PONTIANAK",
                "lokasi" => "SIANTAN",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211000890213", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ab6",
                "witel" => "KALBAR",
                "datel" => "PONTIANAK",
                "lokasi" => "SEI KAKAP",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211001734809", "daya" => "197"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ab7",
                "witel" => "KALBAR",
                "datel" => "MEMPAWAH",
                "lokasi" => "SEI PINYUH",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211110086682", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ab8",
                "witel" => "KALBAR",
                "datel" => "MEMPAWAH",
                "lokasi" => "PLAZA MEMPAWAH",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211100034910", "daya" => "16.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ab9",
                "witel" => "KALBAR",
                "datel" => "MEMPAWAH",
                "lokasi" => "MEMPAWAH",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211100034836", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0aba",
                "witel" => "KALBAR",
                "datel" => "MEMPAWAH",
                "lokasi" => "SEI DURI",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "212500025261", "daya" => "41.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0abb",
                "witel" => "KALBAR",
                "datel" => "SINGKAWANG",
                "lokasi" => "SINGKAWANG",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "212000192219", "daya" => "105"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0abc",
                "witel" => "KALBAR",
                "datel" => "SINGKAWANG",
                "lokasi" => "ROBAN",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "212000284796", "daya" => "23"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0abd",
                "witel" => "KALBAR",
                "datel" => "SINGKAWANG",
                "lokasi" => "BENGKAYANG",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "212300010283", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0abe",
                "witel" => "KALBAR",
                "datel" => "SINGKAWANG",
                "lokasi" => "PEMANGKAT",
                "timezone" => "WIB",
                "listrik" => [
                    ["nomor_pln" => "212100000011", "daya" => "66"],
                    ["daya" => "23", "nomor_pln" => "212120017230"],
                ],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0abf",
                "witel" => "KALBAR",
                "datel" => "SINGKAWANG",
                "lokasi" => "TEBAS",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "212110023465", "daya" => "41.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ac0",
                "witel" => "KALBAR",
                "datel" => "SINGKAWANG",
                "lokasi" => "SAMBAS",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "212200021749", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ac1",
                "witel" => "KALBAR",
                "datel" => "SANGGAU",
                "lokasi" => "NGABANG",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "211400020213", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ac2",
                "witel" => "KALBAR",
                "datel" => "SANGGAU",
                "lokasi" => "BALAIKARANGAN",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "213600009173", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ac3",
                "witel" => "KALBAR",
                "datel" => "SANGGAU",
                "lokasi" => "SANGGAU",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "213000002111", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ac4",
                "witel" => "KALBAR",
                "datel" => "SANGGAU",
                "lokasi" => "SEKADAU",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "213700037488", "daya" => "33"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ac5",
                "witel" => "KALBAR",
                "datel" => "SINTANG",
                "lokasi" => "NANGAPINOH",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "213800011600", "daya" => "82.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ac6",
                "witel" => "KALBAR",
                "datel" => "SINTANG",
                "lokasi" => "SINTANG",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "213100013512", "daya" => "82.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ac7",
                "witel" => "KALBAR",
                "datel" => "SINTANG",
                "lokasi" => "PUTUSIBAU",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "213300067755", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ac8",
                "witel" => "KALBAR",
                "datel" => "KETAPANG",
                "lokasi" => "KETAPANG",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "214000027993", "daya" => "82.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ac9",
                "witel" => "KALBAR",
                "datel" => "KETAPANG",
                "lokasi" => "KENDAWANGAN",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "214030008402", "daya" => "33"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0aca",
                "witel" => "KALBAR",
                "datel" => "KETAPANG",
                "lokasi" => "SUKADANA",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "214100003926", "daya" => "33"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0acb",
                "witel" => "BALIKPAPAN",
                "datel" => "BALIKPAPAN",
                "lokasi" => "Gedung Treg VI",
                "timezone" => "WITA",
                "listrik" => [
                    ["nomor_pln" => "232010533087", "daya" => "865"],
                    ["nomor_pln" => "232010533095", "daya" => "15.4"],
                ],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0acc",
                "witel" => "BALIKPAPAN",
                "datel" => "BALIKPAPAN",
                "lokasi" => "STO Batu Ampar",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "232010766546", "daya" => "555"]],
                "kode" => "BAM",
            ],
            [
                "_id" => "601c3fb236a7bb18138e0acd",
                "witel" => "BALIKPAPAN",
                "datel" => "BALIKPAPAN",
                "lokasi" => "Stasiun Bumi Balikpapan",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "232000012558", "daya" => "147"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ace",
                "witel" => "BALIKPAPAN",
                "datel" => "BALIKPAPAN",
                "lokasi" => "Plasa A Yani Outdoor",
                "timezone" => "WITA",
            ],
            [
                "_id" => "601c3fb236a7bb18138e0acf",
                "witel" => "BALIKPAPAN",
                "datel" => "BALIKPAPAN",
                "lokasi" => "Plasa A Yani Indoor",
                "timezone" => "WITA",
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ad0",
                "witel" => "BALIKPAPAN",
                "datel" => "BALIKPAPAN",
                "lokasi" => "STO 1 Balikpapan",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "232000089040", "daya" => "555"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ad2",
                "witel" => "BALIKPAPAN",
                "datel" => "BALIKPAPAN",
                "lokasi" => "STO Balikpapan Baru",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "232010700298", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ad3",
                "witel" => "BALIKPAPAN",
                "datel" => "BALIKPAPAN",
                "lokasi" => "STO 2 KS Tubun",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "232000604681", "daya" => "105"]],
                "kode" => "KTB",
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ad4",
                "witel" => "BALIKPAPAN",
                "datel" => "BALIKPAPAN",
                "lokasi" => "SKKL Batakan",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "232000342019", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ad5",
                "witel" => "BALIKPAPAN",
                "datel" => "TANAH GROGOT",
                "lokasi" => "STO Tanah Grogot",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "232300019067", "daya" => "105"]],
                "kode" => "TGT",
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ad6",
                "witel" => "BALIKPAPAN",
                "datel" => "TANAH GROGOT",
                "lokasi" => "STO Longikis",
                "timezone" => "WITA",
                "kode" => "LKS",
                "listrik" => [["nomor_pln" => "232220048390"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ad7",
                "witel" => "BALIKPAPAN",
                "datel" => "TANAH GROGOT",
                "lokasi" => "STO Penajam",
                "timezone" => "WITA",
                "kode" => "PNJ",
                "listrik" => [["nomor_pln" => "232230025899"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ad9",
                "witel" => "BALIKPAPAN",
                "datel" => "TANAH GROGOT",
                "lokasi" => "STO Muara Jawa",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "232100031570", "daya" => "41.5"]],
                "kode" => "MJW",
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ada",
                "witel" => "KALTENG",
                "datel" => "PALANGKARAYA",
                "lokasi" => "STO PALANGKA RAYA",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "224010025926", "daya" => "197"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0adb",
                "witel" => "KALTENG",
                "datel" => "PALANGKARAYA",
                "lokasi" => "WITEL PALANGKA RAYA",
                "timezone" => "WIB",
                "listrik" => [
                    ["nomor_pln" => "224010038627", "daya" => "53"],
                    ["nomor_pln" => "225700036542", "daya" => "2.2"],
                ],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0adc",
                "witel" => "KALTENG",
                "datel" => "PALANGKARAYA",
                "lokasi" => "PLASA TELKOM PALANGKA RAYA",
                "timezone" => "WIB",
            ],
            [
                "_id" => "601c3fb236a7bb18138e0add",
                "witel" => "KALTENG",
                "datel" => "PALANGKARAYA",
                "lokasi" => "ARNET CEMPAKA",
                "timezone" => "WIB",
                "listrik" => [
                    ["nomor_pln" => "224010058513", "daya" => "105"],
                    ["nomor_pln" => "224010137578", "daya" => "13.2"],
                ],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ade",
                "witel" => "KALTENG",
                "datel" => "PALANGKARAYA",
                "lokasi" => "KM 5 PLK",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "224030164038", "daya" => "55"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0adf",
                "witel" => "KALTENG",
                "datel" => "SAMPIT",
                "lokasi" => "SAMPIT",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "224090045159", "daya" => "197"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ae0",
                "witel" => "KALTENG",
                "datel" => "SAMPIT",
                "lokasi" => "STO SAMUDA",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "224130027869", "daya" => "33"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ae1",
                "witel" => "KALTENG",
                "datel" => "SAMPIT",
                "lokasi" => "KUALA PEMBUANG",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "224860013613", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ae2",
                "witel" => "KALTENG",
                "datel" => "MUARA TEWEH",
                "lokasi" => "MUARA TEWEH",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "225700019296", "daya" => "82.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ae3",
                "witel" => "KALTENG",
                "datel" => "MUARA TEWEH",
                "lokasi" => "PURUK CAHU",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "225900511054", "daya" => "0"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ae4",
                "witel" => "KALTENG",
                "datel" => "MUARA TEWEH",
                "lokasi" => "BUNTOK",
                "timezone" => "WIB",
                "listrik" => [
                    ["nomor_pln" => "225500009614", "daya" => "82.5"],
                    ["nomor_pln" => "225513778673", "daya" => "41.5"],
                ],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ae5",
                "witel" => "KALTENG",
                "datel" => "MUARA TEWEH",
                "lokasi" => "TAMIANG LAYANG",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "225604254516", "daya" => "41.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ae6",
                "witel" => "KALTENG",
                "datel" => "MUARA TEWEH",
                "lokasi" => "AMPAH",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "225513778673", "daya" => "41.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ae7",
                "witel" => "KALTENG",
                "datel" => "PANGKALAN BUN",
                "lokasi" => "PLASA TELKOM PANGKALANBUN",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "224250033274", "daya" => "23"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ae8",
                "witel" => "KALTENG",
                "datel" => "PANGKALAN BUN",
                "lokasi" => "STO PANGKALANBUN",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "224250049157", "daya" => "105"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0ae9",
                "witel" => "KALTENG",
                "datel" => "PANGKALAN BUN",
                "lokasi" => "KUMAI",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "224300016213", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0aea",
                "witel" => "KALTENG",
                "datel" => "PALANGKARAYA",
                "lokasi" => "KUALA KURUN",
                "timezone" => "WIB",
                "listrik" => [
                    ["nomor_pln" => "224580017549", "daya" => "13.2"],
                    ["nomor_pln" => "224600009076", "daya" => "13.2"],
                ],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0aeb",
                "witel" => "KALTENG",
                "datel" => "PALANGKARAYA",
                "lokasi" => "PULANG PISAU",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "225300020351", "daya" => "41.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0aec",
                "witel" => "KALTENG",
                "datel" => "PALANGKARAYA",
                "lokasi" => "KASONGAN",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "224400007223", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0aed",
                "witel" => "KALTENG",
                "datel" => "PALANGKARAYA",
                "lokasi" => "KUALA KAPUAS",
                "timezone" => "WIB",
                "listrik" => [["nomor_pln" => "225010003882", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0aee",
                "witel" => "KALTENG",
                "datel" => "SAMPIT",
                "lokasi" => "KUALA KUAYAN",
                "timezone" => "WIB",
            ],
            [
                "_id" => "601c3fb236a7bb18138e0aef",
                "witel" => "KALSEL",
                "datel" => "BANJARMASIN",
                "lokasi" => "GRHA WITEL KALSEL",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "221000363102", "daya" => "105"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0af0",
                "witel" => "KALSEL",
                "datel" => "BANJARMASIN",
                "lokasi" => "STO 1 CENTRUM BJM",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "221000092887", "daya" => "555"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0af1",
                "witel" => "KALSEL",
                "datel" => "BANJARMASIN",
                "lokasi" => "STO 2 ULIN BJM",
                "timezone" => "WITA",
                "listrik" => [
                    ["nomor_pln" => "221101585870", "daya" => "164"],
                    ["nomor_pln" => "221100880221", "daya" => "555"],
                ],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0af2",
                "witel" => "KALSEL",
                "datel" => "BANJARMASIN",
                "lokasi" => "SBB NAGASARI",
                "timezone" => "WITA",
                "listrik" => [
                    ["nomor_pln" => "221000658107", "daya" => "164"],
                    ["nomor_pln" => "221001585545", "daya" => "33"],
                ],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0af3",
                "witel" => "KALSEL",
                "datel" => "BANJARMASIN",
                "lokasi" => "GUDANG GAMBUT",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "222210220644", "daya" => "23"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0af4",
                "witel" => "KALSEL",
                "datel" => "BANJARMASIN",
                "lokasi" => "KAYUTANGI",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "221001354508", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0af5",
                "witel" => "KALSEL",
                "datel" => "BANJARMASIN",
                "lokasi" => "PLASA BANJARMASIN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "221000387203", "daya" => "105"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0af6",
                "witel" => "KALSEL",
                "datel" => "BANJARBARU",
                "lokasi" => "BANJARBARU",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "232100031570", "daya" => "147"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0af7",
                "witel" => "KALSEL",
                "datel" => "BANJARBARU",
                "lokasi" => "LANDASAN ULIN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "221200322653", "daya" => "23"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0af8",
                "witel" => "KALSEL",
                "datel" => "BANJARBARU",
                "lokasi" => "MARTAPURA",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "221300151021", "daya" => "33"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0af9",
                "witel" => "KALSEL",
                "datel" => "BANJARBARU",
                "lokasi" => "MARABAHAN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "221500009264", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0afa",
                "witel" => "KALSEL",
                "datel" => "TABALONG",
                "lokasi" => "TANJUNG TABALONG",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "222410029178", "daya" => "105"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0afb",
                "witel" => "KALSEL",
                "datel" => "TABALONG",
                "lokasi" => "RANTAU",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "222110040406", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0afc",
                "witel" => "KALSEL",
                "datel" => "TABALONG",
                "lokasi" => "AMUNTAI",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "222310077622", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0afd",
                "witel" => "KALSEL",
                "datel" => "TABALONG",
                "lokasi" => "PARINGIN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "222510121559", "daya" => "0"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0afe",
                "witel" => "KALSEL",
                "datel" => "TABALONG",
                "lokasi" => "NEGARA",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "222230103822", "daya" => "41.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0aff",
                "witel" => "KALSEL",
                "datel" => "TABALONG",
                "lokasi" => "BARABAI",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "222010082473", "daya" => "82.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b00",
                "witel" => "KALSEL",
                "datel" => "TABALONG",
                "lokasi" => "PLASA TELKOM KANDANGAN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "222210220644", "daya" => "41.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b01",
                "witel" => "KALSEL",
                "datel" => "TABALONG",
                "lokasi" => "STO KANDANGAN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "222210066232", "daya" => "82.5"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b02",
                "witel" => "KALSEL",
                "datel" => "BATULICIN",
                "lokasi" => "SATUI",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "223400004866", "daya" => "33"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b03",
                "witel" => "KALSEL",
                "datel" => "BATULICIN",
                "lokasi" => "PAGATAN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "223210001330", "daya" => "33"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b04",
                "witel" => "KALSEL",
                "datel" => "BATULICIN",
                "lokasi" => "BATULICIN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "223205026760", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b05",
                "witel" => "KALSEL",
                "datel" => "BATULICIN",
                "lokasi" => "KOTABARU",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "223010042666", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b06",
                "witel" => "KALSEL",
                "datel" => "BATULICIN",
                "lokasi" => "PELAIHARI",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "221400026919", "daya" => "131"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b07",
                "witel" => "KALSEL",
                "datel" => "BATULICIN",
                "lokasi" => "BATI-BATI",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "221410079636", "daya" => "23"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b08",
                "witel" => "KALSEL",
                "datel" => "BATULICIN",
                "lokasi" => "SKKL TAKISUNG",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "221430025971", "daya" => "131"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b09",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "STO DAHLIA",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231000080133", "daya" => "345"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b0a",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "STO SUTAMI",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231560785348", "daya" => "105"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b0b",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "STO SEBERANG",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231020173406", "daya" => "66"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b0c",
                "witel" => "SAMARINDA",
                "datel" => "TENGGARONG",
                "lokasi" => "STO MELAK",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231410003155", "daya" => "41.5"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b0d",
                "witel" => "SAMARINDA",
                "datel" => "BONTANG",
                "lokasi" => "STO SANGATTA",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "234200043359", "daya" => "197"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b0e",
                "witel" => "SAMARINDA",
                "datel" => "TENGGARONG",
                "lokasi" => "STO TENGGARONG",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231120068940", "daya" => "82.5"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b0f",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "STO SEI KAPIH",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231570879407"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b10",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "STO PALARAN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231038210965", "daya" => "33"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b11",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "STO SEMPAJA",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231000879438"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b12",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "ARNET SAMARINDA",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231000216974", "daya" => "197"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b13",
                "witel" => "SAMARINDA",
                "datel" => "BONTANG",
                "lokasi" => "DATEL BONTANG",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "234000023031", "daya" => "197"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b14",
                "witel" => "SAMARINDA",
                "datel" => "BONTANG",
                "lokasi" => "STO LOKTUAN",
                "timezone" => "WITA",
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b15",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "PLASA AWANG LONG",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231000283000", "daya" => "66"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "601c3fb236a7bb18138e0b16",
                "witel" => "SAMARINDA",
                "datel" => "BONTANG",
                "lokasi" => "SKKL KENYAMUKAN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "234201448815", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b17",
                "witel" => "KALTARA",
                "datel" => "TARAKAN",
                "lokasi" => "WITEL TARAKAN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "251000026207", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b18",
                "witel" => "KALTARA",
                "datel" => "TARAKAN",
                "lokasi" => "PLASA TARAKAN",
                "timezone" => "WITA",
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b19",
                "witel" => "KALTARA",
                "datel" => "TARAKAN",
                "lokasi" => "STO TARAKAN",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "251000005550", "daya" => "197"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b1a",
                "witel" => "KALTARA",
                "datel" => "BARBULU",
                "lokasi" => "TANJUNG SELOR",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "233200017726", "daya" => "53"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b1b",
                "witel" => "KALTARA",
                "datel" => "BARBULU",
                "lokasi" => "TANJUNG REDEP",
                "timezone" => "WITA",
                "listrik" => [["daya" => "82.5", "nomor_pln" => "233000029604"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b1c",
                "witel" => "KALTARA",
                "datel" => "MANUK",
                "lokasi" => "MALINAU",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "233500002718", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b1d",
                "witel" => "KALTARA",
                "datel" => "MANUK",
                "lokasi" => "NUNUKAN",
                "timezone" => "WITA",
                "listrik" => [
                    ["nomor_pln" => "233600019978", "daya" => "82.5"],
                    ["nomor_pln" => "233700016535", "daya" => "23"],
                ],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b1e",
                "witel" => "KALTARA",
                "datel" => "MANUK",
                "lokasi" => "TANA TIDUNG",
                "timezone" => "WITA",
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b1f",
                "witel" => "KALTARA",
                "datel" => "TARAKAN",
                "lokasi" => "SKKL TG BATU",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "235000011258", "daya" => "66"]],
            ],
            [
                "_id" => "601c3fb236a7bb18138e0b20",
                "witel" => "KALTARA",
                "datel" => "BARBULU",
                "lokasi" => "MAKAJANG - BERAU",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "233000532203", "daya" => "66"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "61af2decc6fbe92f4c0d73af",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "STO LEMPAKE",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231100879418"]],
            ],
            [
                "0" => "timezone",
                "1" => "WITA",
                "_id" => "61af2df3c9ec7b69ba49aadf",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "STO PAL LIMA",
                "timezone" => "WITA",
                "listrik" => [["nomor_pln" => "231560879441"]],
            ],
            [
                "_id" => "62a8440e52def819352b267d",
                "witel" => "KALTARA",
                "datel" => "MANUK",
                "lokasi" => "PLASA NUNUKAN",
                "timezone" => "WITA",
            ],
            [
                "_id" => "62c25069facae60089712afb",
                "witel" => "SAMARINDA",
                "datel" => "SAMARINDA",
                "lokasi" => "STO Temindung",
                "timezone" => "WITA",
            ],
            [
                "_id" => "633eaf96d991284610783190",
                "witel" => "KALTENG",
                "datel" => "PANGKALAN BUN",
                "lokasi" => "SKKL KERAYA",
            ],
        ];

        foreach ($lokasis as $lokasi) {
            $datelid = Datel::firstOrCreate([
                'name' => $lokasi['datel'],
            ], [
                'witel' => $lokasi['witel'],
            ]);

            $new = Lokasi::create([
                'datel_id' => $datelid->id,
                'name' => $lokasi['lokasi'],
                'timezone' => $lokasi['timezone'] ?? "WITA",
            ]);

            if (isset($lokasi['listrik'])) {
                foreach ($lokasi['listrik'] as $token) {
                    Token::create([
                        'lokasi_id' => $new->id,
                        'nopln' => $token['nomor_pln'] ?? null,
                        'ukuran' => $token['ukuran'] ?? null,
                        'daya' => $token['daya'] ?? null,
                    ]);
                }
            }
        }

    }
}
